# Generated by Django 4.2.4 on 2023-11-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yousta', '0003_cloths_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='clothvarient',
            new_name='cloth',
        ),
    ]
