# Generated by Django 4.2.4 on 2023-11-09 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yousta', '0004_rename_clothvarient_reviews_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='cloth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yousta.cloths'),
        ),
    ]
